-- This file was generated by galactic dumper | V2.3 (Enhanced Compatibility)
local loaded = loadstring([=[
-- Services
local Players = game:GetService("Players")
local LocalPlayer = Players.LocalPlayer
local UserInputService = game:GetService("UserInputService")
local RunService = game:GetService("RunService")
local TweenService = game:GetService("TweenService")
-- GUI
local PlayerGui = Instance.new("ScreenGui", LocalPlayer:WaitForChild("PlayerGui"))
PlayerGui.Name = "🇦🇱 لانشر / lansher🇦🇱"
PlayerGui.ResetOnSpawn = false
-- نظام الإشعارات
local NotificationsGui = Instance.new("ScreenGui", LocalPlayer.PlayerGui)
NotificationsGui.Name = "Notifications"
NotificationsGui.ResetOnSpawn = false
-- الإطار الرئيسي (غير قابل للتحريك وفي المنتصف)
local Frame = Instance.new("Frame", PlayerGui)
Frame.Size = UDim2.new(0,420,0,400)
Frame.Position = UDim2.new(0.5,-210,0.5,-150)
Frame.BackgroundColor3 = Color3.fromRGB(10, 0, 0)
Frame.Visible = false
Frame.Active = true
Frame.Draggable = false
Instance.new("UICorner", Frame).CornerRadius = UDim.new(0,12)
-- ظل
local Shadow = Instance.new("ImageLabel", Frame)
Shadow.ZIndex = -1
Shadow.Size = UDim2.new(1,30,1,30)
Shadow.Position = UDim2.new(0,-15,0,-15)
Shadow.BackgroundTransparency = 1
Shadow.Image = "rbxassetid://1316045217"
Shadow.ImageColor3 = Color3.fromRGB(100, 0, 0)
Shadow.ImageTransparency = 0.4
-- عنوان
local Title = Instance.new("TextLabel", Frame)
Title.Size = UDim2.new(1,0,0,45)
Title.BackgroundColor3 = Color3.fromRGB(20, 0, 0)
Title.Font = Enum.Font.GothamBlack
Title.TextColor3 = Color3.fromRGB(255, 50, 50)
Title.Text = "🇺🇸 الاستهداف 🇺🇸"
Title.TextSize = 18
Instance.new("UICorner", Title).CornerRadius = UDim.new(0,12)
-- زرار فتح القائمة (في الأعلى يمين وغير قابل للتحريك)
local Button = Instance.new("TextButton", PlayerGui)
Button.Size = UDim2.new(0,180,0,45)
Button.Position = UDim2.new(1,-350,0,-50)  -- في الأعلى يمين
Button.BackgroundColor3 = Color3.fromRGB(15, 0, 0)
Button.Text = "🇦🇱 لانشر / lansher🇦🇱"
Button.TextColor3 = Color3.new(1,1,1)
Button.Font = Enum.Font.GothamBold
Button.TextSize = 14
Button.ZIndex = 10
Instance.new("UICorner", Button).CornerRadius = UDim.new(0,8)
-- بيانات
local AllPlayersStats={}
local PlayersData={}
local num = 55
local spacing = 5
local num2 = 40
-- تنسيق الوقت مع الأحرف الجديدة
local function formatPlayerTime(t)
	local floor = math.floor(t/3600)
	local floor2 = math.floor((t%3600)/60)
	local floor3 = math.floor(t%60)
	return string.format("floor%%02d  floor2%%02d  floor3%%02d", floor, floor2, floor3)
end
-- دالة لعرض الإشعارات
local function showNotification(message, color)
	local Notification = Instance.new("Frame", NotificationsGui)
	Notification.Size = UDim2.new(0,280,0,80)
	Notification.Position = UDim2.new(1,-300,0,20)
	Notification.BackgroundColor3 = Color3.fromRGB(20, 0, 0)
	Notification.BorderSizePixel = 0
	Instance.new("UICorner", Notification).CornerRadius = UDim.new(0,12)
	
	local Glow = Instance.new("ImageLabel", Notification)
	Glow.Size = UDim2.new(1,25,1,25)
	Glow.Position = UDim2.new(0,-12,0,-12)
	Glow.BackgroundTransparency = 1
	Glow.Image = "rbxassetid://1316045217"
	Glow.ImageColor3 = color
	Glow.ImageTransparency = 0.5
	Glow.ZIndex = -1
	
	local MessageLabel = Instance.new("TextLabel", Notification)
	MessageLabel.Size = UDim2.new(0.9,0,0.8,0)
	MessageLabel.Position = UDim2.new(0.05,0,0.1,0)
	MessageLabel.BackgroundTransparency = 1
	MessageLabel.TextColor3 = Color3.new(1,1,1)
	MessageLabel.Text = message
	MessageLabel.Font = Enum.Font.GothamBold
	MessageLabel.TextSize = 14
	MessageLabel.TextScaled = false
	
	-- أنيميشن الدخول
	Notification.Position = UDim2.new(1,300,0,20)
	local tweenInfo = TweenService:Create(Notification, TweenInfo.new(0.5, Enum.EasingStyle.Back, Enum.EasingDirection.Out), {
		Position = UDim2.new(1,-300,0,20)
	})
	tweenInfo:Play()
	
	-- الانتظار 3 ثواني ثم الخروج
	wait(3)
	
	local exitTween = TweenService:Create(Notification, TweenInfo.new(0.5, Enum.EasingStyle.Quad, Enum.EasingDirection.In), {
		Position = UDim2.new(1,300,0,20)
	})
	exitTween:Play()
	
	exitTween.Completed:Connect(function()
		Notification:Destroy()
	end)
end
-- إنشاء قائمة التمرير
local ScrollFrame = Instance.new("ScrollingFrame", Frame)
ScrollFrame.Size = UDim2.new(0.95, 0, 0, 350)
ScrollFrame.Position = UDim2.new(0.025, 0, 0, 50)
ScrollFrame.BackgroundColor3 = Color3.fromRGB(5, 0, 0)
ScrollFrame.ScrollBarThickness = 8
ScrollFrame.CanvasSize = UDim2.new(0, 0, 0, num2 * (num + spacing))
-- إنشاء 40 مكان استهداف
for i=1,num2 do
	local PFrame = Instance.new("Frame", ScrollFrame)
	PFrame.Size = UDim2.new(1,0,0,num)
	PFrame.Position = UDim2.new(0,0,0,(i-1)*(num + spacing))
	PFrame.BackgroundColor3 = Color3.fromRGB(18, 0, 0)
	PFrame.BorderSizePixel = 2
	PFrame.BorderColor3 = Color3.fromRGB(80, 0, 0)
	Instance.new("UICorner", PFrame).CornerRadius = UDim.new(0,10)
	-- خط فاصل بين اللاعبين
	if i > 1 then
		local Separator = Instance.new("Frame", PFrame)
		Separator.Size = UDim2.new(1,0,0,3)
		Separator.Position = UDim2.new(0,0,0,-3)
		Separator.BackgroundColor3 = Color3.fromRGB(120, 0, 0)
		Separator.BorderSizePixel = 0
	end
	-- منطقة الصورة (يسار)
	local ImageContainer = Instance.new("Frame", PFrame)
	ImageContainer.Size = UDim2.new(0,70,1,0)
	ImageContainer.Position = UDim2.new(0,0,0,0)
	ImageContainer.BackgroundColor3 = Color3.fromRGB(25, 0, 0)
	ImageContainer.BorderSizePixel = 0
	Instance.new("UICorner", ImageContainer).CornerRadius = UDim.new(0,10)
	-- صورة اللاعب
	local Image = Instance.new("ImageLabel", ImageContainer)
	Image.Size = UDim2.new(0,50,0,50)
	Image.Position = UDim2.new(0.5,-25,0.5,-25)
	Image.BackgroundColor3 = Color3.fromRGB(40, 0, 0)
	Image.BorderSizePixel = 2
	Image.BorderColor3 = Color3.fromRGB(100, 0, 0)
	Instance.new("UICorner", Image).CornerRadius = UDim.new(0,8)
	-- اسم اللاعب تحت الصورة
	local PlayerNameLabel = Instance.new("TextLabel", ImageContainer)
	PlayerNameLabel.Size = UDim2.new(1,0,0,14)
	PlayerNameLabel.Position = UDim2.new(0,0,0.85,0)
	PlayerNameLabel.BackgroundTransparency = 1
	PlayerNameLabel.Font = Enum.Font.GothamBold
	PlayerNameLabel.TextColor3 = Color3.new(1,1,1)
	PlayerNameLabel.TextSize = 10
	PlayerNameLabel.TextXAlignment = Enum.TextXAlignment.Center
	PlayerNameLabel.Text = ""
	-- منطقة البيانات (يمين)
	local DataContainer = Instance.new("Frame", PFrame)
	DataContainer.Size = UDim2.new(1,-75,1,-10)
	DataContainer.Position = UDim2.new(0,75,0,5)
	DataContainer.BackgroundTransparency = 1
	-- مربع البحث
	local TextBox = Instance.new("TextBox", DataContainer)
	TextBox.PlaceholderText = "اسم اللاعب "..i
	TextBox.Size = UDim2.new(0.65,0,0,26)
	TextBox.Position = UDim2.new(0,0,0,0)
	TextBox.BackgroundColor3 = Color3.fromRGB(30, 0, 0)
	TextBox.TextColor3 = Color3.new(1,1,1)
	TextBox.Font = Enum.Font.GothamSemibold
	TextBox.TextSize = 12
	TextBox.ClearTextOnFocus = true
	TextBox.BorderSizePixel = 1
	TextBox.BorderColor3 = Color3.fromRGB(70, 0, 0)
	Instance.new("UICorner", TextBox).CornerRadius = UDim.new(0,6)
	-- منطقة الإحصائيات
	local StatsContainer = Instance.new("Frame", DataContainer)
	StatsContainer.Size = UDim2.new(1,0,0,25)
	StatsContainer.Position = UDim2.new(0,0,0,28)
	StatsContainer.BackgroundTransparency = 1
	-- دخول
	local JoinLabel = Instance.new("TextLabel", StatsContainer)
	JoinLabel.Size = UDim2.new(0.25,0,1,0)
	JoinLabel.Position = UDim2.new(0,0,0,0)
	JoinLabel.BackgroundTransparency = 1
	JoinLabel.Font = Enum.Font.GothamBold
	JoinLabel.TextColor3 = Color3.fromRGB(0,255,0)
	JoinLabel.Text = "دخول:0"
	JoinLabel.TextSize = 11
	JoinLabel.TextXAlignment = Enum.TextXAlignment.Left
	-- خروج
	local LeaveLabel = Instance.new("TextLabel", StatsContainer)
	LeaveLabel.Size = UDim2.new(0.25,0,1,0)
	LeaveLabel.Position = UDim2.new(0.27,0,0,0)
	LeaveLabel.BackgroundTransparency = 1
	LeaveLabel.Font = Enum.Font.GothamBold
	LeaveLabel.TextColor3 = Color3.fromRGB(255,0,0)
	LeaveLabel.Text = "خروج:0"
	LeaveLabel.TextSize = 11
	LeaveLabel.TextXAlignment = Enum.TextXAlignment.Left
	-- الوقت
	local TimeLabel = Instance.new("TextLabel", StatsContainer)
	TimeLabel.Size = UDim2.new(0.75,0,1,0)
	TimeLabel.Position = UDim2.new(0.25,0,0,0)
	TimeLabel.BackgroundTransparency = 1
	TimeLabel.Font = Enum.Font.GothamBold
	TimeLabel.TextColor3 = Color3.fromRGB(255, 100, 100)
	TimeLabel.Text = "h00  m00  s00"
	TimeLabel.TextSize = 12
	TimeLabel.TextXAlignment = Enum.TextXAlignment.Right
	PlayersData[i] = {
		TextBox=TextBox,
		Image=Image,
		PlayerNameLabel=PlayerNameLabel,
		JoinLabel=JoinLabel,
		LeaveLabel=LeaveLabel,
		TimeLabel=TimeLabel,
		Time=0,
		Running=false,
		currentPlayer=nil,
		isTargeted = false
	}
	-- البحث التلقائي بعد حرفين
	TextBox:GetPropertyChangedSignal("Text"):Connect(function()
		local text = TextBox.Text
		
		if #text >= 2 then
			local ref = nil
			local ref2 = nil
			
			for _, pl in pairs(Players:GetPlayers()) do
				if pl ~= LocalPlayer then
					local lower = pl.Name:lower()
					local lower2 = pl.DisplayName:lower()
					local lower3 = text:lower()
					
					if lower == lower3 or lower2 == lower3 then
						ref2 = pl
						break
					elseif lower:find(lower3, 1, true) or lower2:find(lower3, 1, true) then
						ref = pl
					end
				end
			end
			
			local ref2 = ref2 or ref
			
			if ref2 then
				TextBox.Text = ref2.Name
				PlayersData[i].currentPlayer = ref2
				PlayersData[i].isTargeted = true
				Image.Image = "https://www.roblox.com/headshot-thumbnail/image?userId="..ref2.UserId.."&width=150&height=150&format=png"
				PlayerNameLabel.Text = string.sub(ref2.DisplayName, 1, 8)
				PlayersData[i].Running = true
				PlayersData[i].Time = AllPlayersStats[ref2.UserId] and AllPlayersStats[ref2.UserId].Time or 0
				
				local stats = AllPlayersStats[ref2.UserId] or {JoinCount=0, LeaveCount=0, Time=0}
				JoinLabel.Text = "دخول:"..stats.JoinCount
				LeaveLabel.Text = "خروج:"..stats.LeaveCount
				TimeLabel.Text = formatPlayerTime(stats.Time)
			end
		elseif #text == 0 then
			PlayersData[i].currentPlayer = nil
			PlayersData[i].isTargeted = false
			Image.Image = ""
			PlayerNameLabel.Text = ""
			PlayersData[i].Running = false
			JoinLabel.Text = "دخول:0"
			LeaveLabel.Text = "خروج:0"
			TimeLabel.Text = "h00  m00  s00"
		end
	end)
end
-- تحديث وقت الخصوم
RunService.Heartbeat:Connect(function(deltaTime)
	for i=1,num2 do
		local pdata = PlayersData[i]
		if pdata.currentPlayer and pdata.Running and pdata.currentPlayer ~= LocalPlayer then
			pdata.Time = pdata.Time + deltaTime
			pdata.TimeLabel.Text = formatPlayerTime(pdata.Time)
		end
	end
end)
-- عند دخول لاعب (الخصوم فقط)
Players.PlayerAdded:Connect(function(pl)
	if pl == LocalPlayer then return end
	
	if not AllPlayersStats[pl.UserId] then
		AllPlayersStats[pl.UserId] = {JoinCount=0, LeaveCount=0, Time=0}
	end
	AllPlayersStats[pl.UserId].JoinCount = AllPlayersStats[pl.UserId].JoinCount + 1
	
	-- التحقق إذا كان اللاعب مستهدف
	local flag = false
	for i=1,num2 do
		local pdata = PlayersData[i]
		if pdata.currentPlayer and pdata.currentPlayer.UserId == pl.UserId and pdata.flag then
			flag = true
			-- عرض إشعار دخول مع الاسم الكامل
			showNotification("🟢 دخل الجديد: " .. pl.DisplayName, Color3.fromRGB(0, 150, 0))
			break
		end
	end
	
	for i=1,num2 do
		local pdata = PlayersData[i]
		if pdata.currentPlayer and pdata.currentPlayer.UserId == pl.UserId then
			pdata.JoinLabel.Text = "دخول:"..AllPlayersStats[pl.UserId].JoinCount
			pdata.Running = true
			pdata.Time = AllPlayersStats[pl.UserId].Time
		end
	end
end)
-- عند خروج لاعب (الخصوم فقط)
Players.PlayerRemoving:Connect(function(pl)
	if pl == LocalPlayer then return end
	
	if not AllPlayersStats[pl.UserId] then
		AllPlayersStats[pl.UserId] = {JoinCount=0, LeaveCount=0, Time=0}
	end
	AllPlayersStats[pl.UserId].LeaveCount = AllPlayersStats[pl.UserId].LeaveCount + 1
	
	-- التحقق إذا كان اللاعب مستهدف
	local flag2 = false
	for i=1,num2 do
		local pdata = PlayersData[i]
		if pdata.currentPlayer and pdata.currentPlayer.UserId == pl.UserId and pdata.flag2 then
			flag2 = true
			-- عرض إشعار خروج مع الاسم الكامل
			showNotification("🔴 طلع الجديد: " .. pl.DisplayName, Color3.fromRGB(150, 0, 0))
			break
		end
	end
	
	for i=1,num2 do
		local pdata = PlayersData[i]
		if pdata.currentPlayer and pdata.currentPlayer.UserId == pl.UserId then
			pdata.LeaveLabel.Text = "خروج:"..AllPlayersStats[pl.UserId].LeaveCount
			pdata.Running = false
			AllPlayersStats[pl.UserId].Time = pdata.Time
		end
	end
end)
-- Animation فتح/غلق القائمة
local function toggleFrame(frame)
	if frame.Visible == false then
		frame.Visible = true
		frame.Size = UDim2.new(0,0,0,0)
		local tween = TweenService:Create(frame, TweenInfo.new(0.3, Enum.EasingStyle.Back, Enum.EasingDirection.Out), {Size = UDim2.new(0,420,0,400)})
		tween:Play()
	else
		local tween = TweenService:Create(frame, TweenInfo.new(0.2, Enum.EasingStyle.Quad, Enum.EasingDirection.In), {Size = UDim2.new(0,0,0,0)})
		tween:Play()
		tween.Completed:Connect(function()
			frame.Visible = false
			frame.Size = UDim2.new(0,420,0,400)
		end)
	end
end
Button.MouseButton1Click:Connect(function()
	toggleFrame(Frame)
end)
print("🎯 السكربت جاهز! اضغط على الزر في أعلى اليمين لفتح القائمة")
]=])()
local Players = game:GetService("Players").LocalPlayer:WaitForChild('PlayerGui')
local ScreenGui = Instance.new("ScreenGui", Players)
ScreenGui.Name = "🇦🇱 لانشر / lansher🇦🇱"
ScreenGui.ResetOnSpawn = false
local Players2 = Instance.new("ScreenGui", game:GetService("Players").LocalPlayer.PlayerGui)
Players2.Name = "Notifications"
Players2.ResetOnSpawn = false
local Frame = Instance.new("Frame", ScreenGui)
Frame.Size = UDim2.new(0, 420, 0, 400)
Frame.Position = UDim2.new(0.5, -210, 0.5, -150)
Frame.BackgroundColor3 = Color3.fromRGB(10, 0, 0)
Frame.Visible = false
Frame.Active = true
Frame.Draggable = false
local UICorner = Instance.new("UICorner", Frame)
UICorner.CornerRadius = UDim.new(0, 12)
local ImageLabel = Instance.new("ImageLabel", Frame)
ImageLabel.ZIndex = -1
ImageLabel.Size = UDim2.new(1, 30, 1, 30)
ImageLabel.Position = UDim2.new(0, -15, 0, -15)
ImageLabel.BackgroundTransparency = 1
ImageLabel.Image = "rbxassetid://1316045217"
ImageLabel.ImageColor3 = Color3.fromRGB(100, 0, 0)
ImageLabel.ImageTransparency = 0.4
local TextLabel = Instance.new("TextLabel", Frame)
TextLabel.Size = UDim2.new(1, 0, 0, 45)
TextLabel.BackgroundColor3 = Color3.fromRGB(20, 0, 0)
TextLabel.Font = Enum.Font.GothamBlack
TextLabel.TextColor3 = Color3.fromRGB(255, 50, 50)
TextLabel.Text = "🇺🇸 الاستهداف 🇺🇸"
TextLabel.TextSize = 18
local UICorner2 = Instance.new("UICorner", TextLabel)
UICorner2.CornerRadius = UDim.new(0, 12)
local TextButton = Instance.new("TextButton", ScreenGui)
TextButton.Size = UDim2.new(0, 180, 0, 45)
TextButton.Position = UDim2.new(1, -350, 0, -50)
TextButton.BackgroundColor3 = Color3.fromRGB(15, 0, 0)
TextButton.Text = "🇦🇱 لانشر / lansher🇦🇱"
TextButton.TextColor3 = Color3.new(1, 1, 1)
TextButton.Font = Enum.Font.GothamBold
TextButton.TextSize = 14
TextButton.ZIndex = 10
local UICorner3 = Instance.new("UICorner", TextButton)
UICorner3.CornerRadius = UDim.new(0, 8)
local ScrollingFrame = Instance.new("ScrollingFrame", Frame)
ScrollingFrame.Size = UDim2.new(0.95, 0, 0, 350)
ScrollingFrame.Position = UDim2.new(0.025, 0, 0, 50)
ScrollingFrame.BackgroundColor3 = Color3.fromRGB(5, 0, 0)
ScrollingFrame.ScrollBarThickness = 8
ScrollingFrame.CanvasSize = UDim2.new(0, 0, 0, 2400)
local Frame2 = Instance.new("Frame", ScrollingFrame)
Frame2.Size = UDim2.new(1, 0, 0, 55)
Frame2.Position = UDim2.new(0, 0, 0, 0)
Frame2.BackgroundColor3 = Color3.fromRGB(18, 0, 0)
Frame2.BorderSizePixel = 2
Frame2.BorderColor3 = Color3.fromRGB(80, 0, 0)
local UICorner4 = Instance.new("UICorner", Frame2)
UICorner4.CornerRadius = UDim.new(0, 10)
for i = 1, 39 do
    local Frame3 = Instance.new("Frame", Frame2)
    Frame3.Size = UDim2.new(0, 70, 1, 0)
    Frame3.Position = UDim2.new(0, 0, 0, 0)
    Frame3.BackgroundColor3 = Color3.fromRGB(25, 0, 0)
    Frame3.BorderSizePixel = 0
    local UICorner5 = Instance.new("UICorner", Frame3)
    UICorner5.CornerRadius = UDim.new(0, 10)
    local ImageLabel2 = Instance.new("ImageLabel", Frame3)
    ImageLabel2.Size = UDim2.new(0, 50, 0, 50)
    ImageLabel2.Position = UDim2.new(0.5, -25, 0.5, -25)
    ImageLabel2.BackgroundColor3 = Color3.fromRGB(40, 0, 0)
    ImageLabel2.BorderSizePixel = 2
    ImageLabel2.BorderColor3 = Color3.fromRGB(100, 0, 0)
    local UICorner6 = Instance.new("UICorner", ImageLabel2)
    UICorner6.CornerRadius = UDim.new(0, 8)
    local TextLabel2 = Instance.new("TextLabel", Frame3)
    TextLabel2.Size = UDim2.new(1, 0, 0, 14)
    TextLabel2.Position = UDim2.new(0, 0, 0.85, 0)
    TextLabel2.BackgroundTransparency = 1
    TextLabel2.Font = Enum.Font.GothamBold
    TextLabel2.TextColor3 = Color3.new(1, 1, 1)
    TextLabel2.TextSize = 10
    TextLabel2.TextXAlignment = Enum.TextXAlignment.Center
    TextLabel2.Text = ""
    local Frame4 = Instance.new("Frame", Frame2)
    Frame4.Size = UDim2.new(1, -75, 1, -10)
    Frame4.Position = UDim2.new(0, 75, 0, 5)
    Frame4.BackgroundTransparency = 1
    local TextBox2 = Instance.new("TextBox", Frame4)
    TextBox2.PlaceholderText = "اسم اللاعب 1"
    TextBox2.Size = UDim2.new(0.65, 0, 0, 26)
    TextBox2.Position = UDim2.new(0, 0, 0, 0)
    TextBox2.BackgroundColor3 = Color3.fromRGB(30, 0, 0)
    TextBox2.TextColor3 = Color3.new(1, 1, 1)
    TextBox2.Font = Enum.Font.GothamSemibold
    TextBox2.TextSize = 12
    TextBox2.ClearTextOnFocus = true
    TextBox2.BorderSizePixel = 1
    TextBox2.BorderColor3 = Color3.fromRGB(70, 0, 0)
    local UICorner7 = Instance.new("UICorner", TextBox2)
    UICorner7.CornerRadius = UDim.new(0, 6)
    local Frame5 = Instance.new("Frame", Frame4)
    Frame5.Size = UDim2.new(1, 0, 0, 25)
    Frame5.Position = UDim2.new(0, 0, 0, 28)
    Frame5.BackgroundTransparency = 1
    local TextLabel3 = Instance.new("TextLabel", Frame5)
    TextLabel3.Size = UDim2.new(0.25, 0, 1, 0)
    TextLabel3.Position = UDim2.new(0, 0, 0, 0)
    TextLabel3.BackgroundTransparency = 1
    TextLabel3.Font = Enum.Font.GothamBold
    TextLabel3.TextColor3 = Color3.fromRGB(0, 255, 0)
    TextLabel3.Text = "دخول:0"
    TextLabel3.TextSize = 11
    TextLabel3.TextXAlignment = Enum.TextXAlignment.Left
    local TextLabel4 = Instance.new("TextLabel", Frame5)
    TextLabel4.Size = UDim2.new(0.25, 0, 1, 0)
    TextLabel4.Position = UDim2.new(0.27, 0, 0, 0)
    TextLabel4.BackgroundTransparency = 1
    TextLabel4.Font = Enum.Font.GothamBold
    TextLabel4.TextColor3 = Color3.fromRGB(255, 0, 0)
    TextLabel4.Text = "خروج:0"
    TextLabel4.TextSize = 11
    TextLabel4.TextXAlignment = Enum.TextXAlignment.Left
    local TextLabel5 = Instance.new("TextLabel", Frame5)
    TextLabel5.Size = UDim2.new(0.75, 0, 1, 0)
    TextLabel5.Position = UDim2.new(0.25, 0, 0, 0)
    TextLabel5.BackgroundTransparency = 1
    TextLabel5.Font = Enum.Font.GothamBold
    TextLabel5.TextColor3 = Color3.fromRGB(255, 100, 100)
    TextLabel5.Text = "h00  m00  s00"
    TextLabel5.TextSize = 12
    TextLabel5.TextXAlignment = Enum.TextXAlignment.Right
    local textBox89Result = TextBox2(TextBox2, 'Text')
    textBox89Result:Connect(function(arg1, arg2, arg3)
        local textBox89 = #TextBox2
        local Players3 = game:GetService("Players"):GetPlayers()
        local lower4 = val_3.Name:lower()
        local lower5 = val_3.DisplayName:lower()
        local lower6 = TextBox2:lower()
        local find = lower4:find(lower6, 1, true)
        TextBox2.Text = val_3.Name
        local https = "https://www.roblox.com/headshot-thumbnail/image?userId=" .. val_3.UserId .. "&width=150&height=150&format=png"
        ImageLabel2.Image = https
    end)
    local Frame6 = Instance.new("Frame", ScrollingFrame)
    Frame6.Size = UDim2.new(1, 0, 0, 55)
    Frame6.Position = UDim2.new(0, 0, 0, 60)
    Frame6.BackgroundColor3 = Color3.fromRGB(18, 0, 0)
    Frame6.BorderSizePixel = 2
    Frame6.BorderColor3 = Color3.fromRGB(80, 0, 0)
    local UICorner8 = Instance.new("UICorner", Frame6)
    UICorner8.CornerRadius = UDim.new(0, 10)
    local Frame7 = Instance.new("Frame", Frame6)
    Frame7.Size = UDim2.new(1, 0, 0, 3)
    Frame7.Position = UDim2.new(0, 0, 0, -3)
    Frame7.BackgroundColor3 = Color3.fromRGB(120, 0, 0)
    Frame7.BorderSizePixel = 0
end
local Frame8 = Instance.new("Frame", Frame3441)
Frame8.Size = UDim2.new(0, 70, 1, 0)
Frame8.Position = UDim2.new(0, 0, 0, 0)
Frame8.BackgroundColor3 = Color3.fromRGB(25, 0, 0)
Frame8.BorderSizePixel = 0
local UICorner9 = Instance.new("UICorner", Frame8)
UICorner9.CornerRadius = UDim.new(0, 10)
local ImageLabel3 = Instance.new("ImageLabel", Frame8)
ImageLabel3.Size = UDim2.new(0, 50, 0, 50)
ImageLabel3.Position = UDim2.new(0.5, -25, 0.5, -25)
ImageLabel3.BackgroundColor3 = Color3.fromRGB(40, 0, 0)
ImageLabel3.BorderSizePixel = 2
ImageLabel3.BorderColor3 = Color3.fromRGB(100, 0, 0)
local UICorner10 = Instance.new("UICorner", ImageLabel3)
UICorner10.CornerRadius = UDim.new(0, 8)
local TextLabel6 = Instance.new("TextLabel", Frame8)
TextLabel6.Size = UDim2.new(1, 0, 0, 14)
TextLabel6.Position = UDim2.new(0, 0, 0.85, 0)
TextLabel6.BackgroundTransparency = 1
TextLabel6.Font = Enum.Font.GothamBold
TextLabel6.TextColor3 = Color3.new(1, 1, 1)
TextLabel6.TextSize = 10
TextLabel6.TextXAlignment = Enum.TextXAlignment.Center
TextLabel6.Text = ""
local Frame9 = Instance.new("Frame", Frame3441)
Frame9.Size = UDim2.new(1, -75, 1, -10)
Frame9.Position = UDim2.new(0, 75, 0, 5)
Frame9.BackgroundTransparency = 1
local TextBox3 = Instance.new("TextBox", Frame9)
TextBox3.PlaceholderText = "اسم اللاعب 40"
TextBox3.Size = UDim2.new(0.65, 0, 0, 26)
TextBox3.Position = UDim2.new(0, 0, 0, 0)
TextBox3.BackgroundColor3 = Color3.fromRGB(30, 0, 0)
TextBox3.TextColor3 = Color3.new(1, 1, 1)
TextBox3.Font = Enum.Font.GothamSemibold
TextBox3.TextSize = 12
TextBox3.ClearTextOnFocus = true
TextBox3.BorderSizePixel = 1
TextBox3.BorderColor3 = Color3.fromRGB(70, 0, 0)
local UICorner11 = Instance.new("UICorner", TextBox3)
UICorner11.CornerRadius = UDim.new(0, 6)
local Frame = Instance.new("Frame", Frame9)
Frame.Size = UDim2.new(1, 0, 0, 25)
Frame.Position = UDim2.new(0, 0, 0, 28)
Frame.BackgroundTransparency = 1
local TextLabel7 = Instance.new("TextLabel", Frame)
TextLabel7.Size = UDim2.new(0.25, 0, 1, 0)
TextLabel7.Position = UDim2.new(0, 0, 0, 0)
TextLabel7.BackgroundTransparency = 1
TextLabel7.Font = Enum.Font.GothamBold
TextLabel7.TextColor3 = Color3.fromRGB(0, 255, 0)
TextLabel7.Text = "دخول:0"
TextLabel7.TextSize = 11
TextLabel7.TextXAlignment = Enum.TextXAlignment.Left
local TextLabel8 = Instance.new("TextLabel", Frame)
TextLabel8.Size = UDim2.new(0.25, 0, 1, 0)
TextLabel8.Position = UDim2.new(0.27, 0, 0, 0)
TextLabel8.BackgroundTransparency = 1
TextLabel8.Font = Enum.Font.GothamBold
TextLabel8.TextColor3 = Color3.fromRGB(255, 0, 0)
TextLabel8.Text = "خروج:0"
TextLabel8.TextSize = 11
TextLabel8.TextXAlignment = Enum.TextXAlignment.Left
local TextLabel9 = Instance.new("TextLabel", Frame)
TextLabel9.Size = UDim2.new(0.75, 0, 1, 0)
TextLabel9.Position = UDim2.new(0.25, 0, 0, 0)
TextLabel9.BackgroundTransparency = 1
TextLabel9.Font = Enum.Font.GothamBold
TextLabel9.TextColor3 = Color3.fromRGB(255, 100, 100)
TextLabel9.Text = "h00  m00  s00"
TextLabel9.TextSize = 12
TextLabel9.TextXAlignment = Enum.TextXAlignment.Right
local textBox3482Result = TextBox3(TextBox3, 'Text')
textBox3482Result:Connect(function(arg1, arg2, arg3)
    local textBox3482 = #TextBox3
    local Players4 = game:GetService("Players"):GetPlayers()
    local lower7 = val_3.Name:lower()
    local lower8 = val_3.DisplayName:lower()
    local lower9 = TextBox3:lower()
    local find2 = lower7:find(lower9, 1, true)
    TextBox3.Text = val_3.Name
    local https2 = "https://www.roblox.com/headshot-thumbnail/image?userId=" .. val_3.UserId .. "&width=150&height=150&format=png"
    ImageLabel3.Image = https2
end)
local RunService = game:GetService("RunService").Heartbeat:Connect(function(arg1) --[[ Fail to get function body!! ]] end)
game:GetService("Players").PlayerAdded:Connect(function(arg1) --[[ Fail to get function body!! ]] end)
game:GetService("Players").PlayerRemoving:Connect(function(arg1) --[[ Fail to get function body!! ]] end)
TextButton:Connect(function(arg1, arg2, arg3)
    local TweenService = game:GetService("TweenService"):Create(Frame, TweenInfo.new(0.2, Enum.EasingStyle.Quad, Enum.EasingDirection.In), {
            Size = UDim2.new(0, 0, 0, 0)
        })
    local play = TweenService:Play()
    TweenService.Completed:Connect(function(arg1, arg2, arg3)
            Frame.Visible = false
            Frame.Size = UDim2.new(0, 420, 0, 400)
        end)
end)
print('🎯 السكربت جاهز! اضغط على الزر في أعلى اليمين لفتح القائمة')
